### ISSUE TITLE
FYI: there is an official API for the color-name list

### ISSUE THREAD

**Issue by meodai** [JerryKhw/figma-color-namer-api#1]
https://github.com/meodai/color-name-api

the endpoint is a bit different than yours, but you don't need to maintain it your self.
As a bonus it comes with different lists:

https://api.color.pizza/v1/?values=aaffcc&list=wikipedia

**Comment by JerryKhw** [comment]
Thanks for the issue!
I know that there is an official API, but I configured a separate API to process a separate name (when there is a duplicate name, when there is transparency).
